### ISSUE TITLE
cannot load such file -- nokogiri

### ISSUE THREAD

**Issue by mikeccuk2005** [MiderWong/homebrew-flutter#5]
`brew tap MiderWong/flutter`

I already tried 
```
gem install nokogiri
gem update --system
```
But still same error. I am using Mojave 10.14

**Comment by gkcgautam** [comment]
Any recommended solution for this?

**Comment by MiderWong** [comment]
Hasn't solvethe solvet problems so far?

**Comment by JounQin** [comment]
https://travis-ci.com/JounQin/.dotfiles/jobs/216352454#L802

It also throws an error on linuxbrew.

**Comment by MiderWong** [comment]
@JounQin 
```shell
https://nokogiri.org/
https://rubygems.org/gems/nokogiri/versions/1.6.8
```
You can install nokogiri by referring to the links above.

**Comment by JounQin** [comment]
@MiderWong I tried. https://github.com/JounQin/.dotfiles/blob/master/.travis.yml#L13

**Comment by MiderWong** [comment]
@JounQin 
有几个问题修正：
①、文件`https://github.com/JounQin/.dotfiles/blob/master/Brewfile`第40行所执行的命令得到的错误展示在文件`https://travis-ci.com/JounQin/.dotfiles/jobs/216856746#L813-L818` 第872行，为此我改了本项目的目录结构，你的`Brewfile`就不需要更改了，你可以重新执行一次试试
②、文件`https://travis-ci.com/JounQin/.dotfiles/jobs/216856746#L813-L818` 第876——879行的错误的原因有可能是XCode没有安装，因为flutter要求使用命令`xcode-select --install`安装XCode
③、我没有使用过linuxbrew，有一个疑问：文件`https://github.com/JounQin/.dotfiles/blob/master/Brewfile`的第11行和第40行分别代表的意义？

**Comment by JounQin** [comment]
@MiderWong 

② Flutter 在 Linux 环境应该也能编译才对吧 https://flutter.dev/docs/get-started/install/linux
③ Brewfile 就是把 Homebrew + cask + mas 打包了一下，第 11 行就是代表 `brew tap MiderWong/flutter`，第 40 行代表 `brew install miderwong/flutter/flutter`

**Comment by MiderWong** [comment]
已经重新发版，之前通过nokogiri访问网页然后xpath获取ip/address的方案已经被放弃，改为通过命令行调用获得信息
